default_email: "ndt8895@gmail.com"
role_admin: 0
role_user: 1
per_page: 5
admin:
  users:
    size: "70x70"
    url_ava: "assets/avata.jpg"
users:
  size: "50x50"
  size_ava: "100x100"
  url_ava: "/assets/user_3.png"
  pic_size: 5
